FROM langchain/langgraphjs-api:20
ADD . /deps/{{PROJECT_NAME}}
ENV LANGSERVE_GRAPHS='{"agent":"./src/graph.ts:graph"}'
WORKDIR /deps/{{PROJECT_NAME}}
RUN npm ci
RUN (test ! -f /api/langgraph_api/js/build.mts && echo "Prebuild script not found, skipping") || tsx /api/langgraph_api/js/build.mts
